# https://github.com/detekt/detekt/blob/main/detekt-core/src/main/resources/default-detekt-config.yml
# https://detekt.dev/docs/rules/style
style:
  active: true
  ClassOrdering:
    active: true
  CollapsibleIfStatements:
    active: true