lane :build do
  gradle(task: "lint")
  gradle(task: "app:ktlintMainSourceSetCheck")
  gradle(task: "detekt")
  gradle(task: "assembleDebug")
  gradle(task: "bundleRelease")
  sign_bundle
  build_apk_from_bundle
  sign_apk
  danger(
    github_api_token: ENV["DANGER_GITHUB_API_TOKEN"],
    verbose: true,
    danger_id: "common",
    dangerfile: "Dangerfile.common",
    pr: 'https://github.com/pnlinh-it/danger_android_test/pull/1'
  )
  danger(
    github_api_token: ENV["DANGER_GITHUB_API_TOKEN"],
    verbose: true,
    danger_id: "sourcecheck",
    dangerfile: "Dangerfile.sourcecheck",
    pr: 'https://github.com/pnlinh-it/danger_android_test/pull/1'
  )
  debug
  upload_to_server
end
