lane :build do
  danger(
    github_api_token: ENV["DANGER_GITHUB_API_TOKEN"],
    verbose: true,
    danger_id: "common",
    dangerfile: "Dangerfile.common",
    pr: 'https://github.com/pnlinh-it/danger_android_test/pull/1'
  )
  debug
  # gradle(task: "lint")
  # gradle(task: "app:ktlintMainSourceSetCheck")
  # gradle(task: "detekt")
  # gradle(task: "assembleDebug")
end
